version: '3.6'

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      # - "7000:15672"
      # - "7001:5672"
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    networks:
        - bridge_net
        - rabbit_net

  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379
    restart: always
    networks:
        - redis_net

  api:
    build:
      dockerfile: cmd/api/Dockerfile
      context: .
    ports:
      - 8080:8080
    networks:
        - bridge_net
        - rabbit_net
    depends_on:
      - rabbitmq
    environment:
      - RMQ_QUEUE_NAME=messageQueue
      - RMQ_USER=user
      - RMQ_PASS=password
      - RMQ_HOST=rabbitmq
      - RMQ_PORT=5672

  worker:
    build:
      dockerfile: cmd/worker/Dockerfile
      context: .
    networks:
        - rabbit_net
        - redis_net
    depends_on:
      - rabbitmq
      - redis
    environment:
      - RMQ_QUEUE_NAME=messageQueue
      - RMQ_USER=user
      - RMQ_PASS=password
      - RMQ_HOST=rabbitmq
      - RMQ_PORT=5672
      - RMQ_EXCHANGE="work_exchange"
      - REDIS_HOST=redis
      - REDIS_PORT=6379

networks:
  bridge_net:
    driver: bridge
  rabbit_net:
  redis_net:
