version: '3.6'

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      # - "7000:15672"
      # - "7001:5672"
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    networks:
        - bridge_net
        - rabbit_net
    # network_mode: host

  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379
    restart: always

  api:
    build:
      dockerfile: cmd/api/Dockerfile
      context: .
    ports:
      - 8080:8080
    networks:
        - bridge_net
        - rabbit_net
    depends_on:
      - rabbitmq
    environment:
      - RMQ_QUEUE_NAME=messageQueue
      - RMQ_USER=user
      - RMQ_PASS=password
      - RMQ_HOST=rabbitmq
      - RMQ_PORT=5672

  # rabbitmq2:
  #     image: rabbitmq:3-management
  #     container_name: 'rabbitmq2'
  #     ports:
  #         - 5672:5672
  #         - 15672:15672
  #     # volumes:
  #     #     - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
  #     #     - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  #     networks:
  #         - bridge_net

networks:
  bridge_net:
    driver: bridge
  rabbit_net:
